kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: api
  namespace: demo-integration 
spec:  
  to:
    kind: Service
    name: '{{ .Values.backend.app.name }}'
    weight: 100
  port:
    targetPort: 8080-tcp
  wildcardPolicy: None