kind: Secret
apiVersion: v1
metadata:
  name: mysql
  labels:
    template: mysql-persistent-template
    template.openshift.io/template-instance-owner: 7de79f8f-1190-4ce9-96b7-a03a2fe34372
  annotations:
    template.openshift.io/expose-database_name: '{.data[''database-name'']}'
    template.openshift.io/expose-password: '{.data[''database-password'']}'
    template.openshift.io/expose-root_password: '{.data[''database-root-password'']}'
    template.openshift.io/expose-username: '{.data[''database-user'']}'
data:
  database-name: ZGVtb2ludGVncmF0aW9uZGI=
  database-password: MXFhekBXU1g=
  database-root-password: MXFhekBXU1g=
  database-user: ZGVtbw==
type: Opaque
