kind: Service
apiVersion: v1
metadata:
  name: mysql
  labels:
  annotations:
    template.openshift.io/expose-uri: 'mysql://{.spec.clusterIP}:{.spec.ports[?(.name=="mysql")].port}'
spec:    
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306
  internalTrafficPolicy: Cluster
  type: ClusterIP  
  sessionAffinity: None
  selector:
    name: mysql
